### PR TITLE
Feedback on resubmission of the AGDS report exercises

### PR DESCRIPTION
**Pull request by pepaaran**
Hi Elias,

Thanks for submitting your report exercises again. I wanted to congratulate you on the improvements that you've made to the markdown files because it was very easy to "reproduce" your results, meaning that I could mostly just click `Knitt` button to produce your reports. To add another learning opportunity, I'm giving you feedback in the coder style, via a pull request. 

- For the first report exercise I had to change the name of a file to read the data, you can see the modifications associated with each commit below. That was the only piece missing for running your code on my machine.
- In general, the reports are of good quality, but you could have taken more care for the presentation. For upcoming classes and projects, you could take a look at this [Markdown syntax intro](https://www.markdownguide.org/basic-syntax/) and use it to divide the report into sections with titles, introductory text, etc. This makes a better impression and you work is easier to read. It will also make it easier for you to go back to old code/report in the future.

You have certainly learned a lot during the course and could submit a reproducible workflow. I hope that it was also enjoyable to work on it. Have a great start in the new semester or whatever will keep you busy this autumn.

Best,
Pepa

### CODE REVIEW

**Comment by sailekoe** [comment]
Hi Pepa

Thank you so much for your helpful feed-back! I’m very happy that you were able to reproduce the code and that the quality of the exercises was good. And I take the tip concerning the layout to heart for the next time!

One last question: Is the grade going to stay the same or are you going to adjust it?



Best,


Elias



Von: Pepa ***@***.***>
Gesendet: Mittwoch, 20. September 2023 12:21
An: ***@***.***>
Cc: ***@***.***>
Betreff: [sailekoe/agds_report_eliaskoeppel] Feedback on resubmission of the AGDS report exercises (PR #1)


Hi Elias,

Thanks for submitting your report exercises again. I wanted to congratulate you on the improvements that you've made to the markdown files because it was very easy to "reproduce" your results, meaning that I could mostly just click Knitt button to produce your reports. To add another learning opportunity, I'm giving you feedback in the coder style, via a pull request.

  *   For the first report exercise I had to change the name of a file to read the data, you can see the modifications associated with each commit below. That was the only piece missing for running your code on my machine.
  *   In general, the reports are of good quality, but you could have taken more care for the presentation. For upcoming classes and projects, you could take a look at this Markdown syntax intro<https://www.markdownguide.org/basic-syntax/> and use it to divide the report into sections with titles, introductory text, etc. This makes a better impression and you work is easier to read. It will also make it easier for you to go back to old code/report in the future.

You have certainly learned a lot during the course and could submit a reproducible workflow. I hope that it was also enjoyable to work on it. Have a great start in the new semester or whatever will keep you busy this autumn.

Best,
Pepa

You can view, comment on, or merge this pull request online at:

  https://github.com/sailekoe/agds_report_eliaskoeppel/pull/1

Commit Summary

  *   452be2c<https://github.com/sailekoe/agds_report_eliaskoeppel/pull/1/commits/452be2c375a2375a4b947388457a4b1f53112ba2> fix file path for knitting
  *   0f17eb7<https://github.com/sailekoe/agds_report_eliaskoeppel/pull/1/commits/0f17eb7d94252f1f85703e5b29f2883a7aa5832c> feedback

File Changes

(1 file<https://github.com/sailekoe/agds_report_eliaskoeppel/pull/1/files>)

  *   M Vignettes/report_exercise_3.5.Rmd<https://github.com/sailekoe/agds_report_eliaskoeppel/pull/1/files#diff-98ae94e49f3399e1281bda836af70e33851527bedb1760d79d2090c86d13b08d> (4)

Patch Links:

  *   https://github.com/sailekoe/agds_report_eliaskoeppel/pull/1.patch
  *   https://github.com/sailekoe/agds_report_eliaskoeppel/pull/1.diff

**Comment by pepaaran** [comment]
You will receive the grade in the next days, no worries.

**Comment by pepaaran** [comment]
By the way, you can accept the pull request to add my changes to your code. Good practice for the future.

**Comment by sailekoe** [comment]
Okay, great!
And yes, I just accepted it :) („merged“ it, right?)


Am 20.09.2023 um 16:59 schrieb Pepa Arán ***@***.***>:

﻿

By the way, you can accept the pull request to add my changes to your code. Good practice for the future.

**Comment by pepaaran** [comment]
Exactly!

**Pull request merged**
